#!/bin/bash

# 显示文件的全路径
cd $UXSRCHOME

result2=`find . -name "*.c" |xargs grep -in "$1"|grep -Ev $GREPFILTER|grep -in "$1"`
#echo "result2 " "$result2"
# uniq 去除重复行
result3=`echo "$result2"|awk -F ":" '{print $2}'|uniq`
echo  "$result3"
echo "$result3" > $HOME/.myscript/file.txt

# $2 为vim打开文件的参数, 可以为空, 也可以为 -O: 垂直分割打开  -o:水平分割打开
#vim $2 $result3
#vim $HOME/.myscript/file.txt
